/**
 * Action type constants for Node Editor
 */
export const NODE_EDITOR_ACTIONS = {
  // Node operations
  ADD_NODE: "ADD_NODE",
  UPDATE_NODE: "UPDATE_NODE",
  DELETE_NODE: "DELETE_NODE",
  MOVE_NODE: "MOVE_NODE",
  MOVE_NODES: "MOVE_NODES",
  DUPLICATE_NODES: "DUPLICATE_NODES",
  
  // Connection operations
  ADD_CONNECTION: "ADD_CONNECTION",
  DELETE_CONNECTION: "DELETE_CONNECTION",
  
  // Group operations
  GROUP_NODES: "GROUP_NODES",
  UNGROUP_NODE: "UNGROUP_NODE",
  UPDATE_GROUP_MEMBERSHIP: "UPDATE_GROUP_MEMBERSHIP",
  MOVE_GROUP_WITH_CHILDREN: "MOVE_GROUP_WITH_CHILDREN",
  
  // Editor state
  SET_NODE_DATA: "SET_NODE_DATA",
  RESTORE_STATE: "RESTORE_STATE",
  AUTO_LAYOUT: "AUTO_LAYOUT",
} as const;

export type NodeEditorActionType = typeof NODE_EDITOR_ACTIONS[keyof typeof NODE_EDITOR_ACTIONS];

/**
 * Action type constants for Editor Action State
 */
export const EDITOR_ACTION_STATE_ACTIONS = {
  // Selection
  SELECT_NODE: "SELECT_NODE",
  SELECT_CONNECTION: "SELECT_CONNECTION",
  SELECT_NODES_IN_BOX: "SELECT_NODES_IN_BOX",
  SET_SELECTED_NODES: "SET_SELECTED_NODES",
  SET_SELECTED_CONNECTIONS: "SET_SELECTED_CONNECTIONS",
  CLEAR_SELECTION: "CLEAR_SELECTION",
  
  // Selection box
  START_SELECTION_BOX: "START_SELECTION_BOX",
  UPDATE_SELECTION_BOX: "UPDATE_SELECTION_BOX",
  END_SELECTION_BOX: "END_SELECTION_BOX",
  
  // Node drag
  START_NODE_DRAG: "START_NODE_DRAG",
  UPDATE_NODE_DRAG: "UPDATE_NODE_DRAG",
  END_NODE_DRAG: "END_NODE_DRAG",
  
  // Node resize
  START_NODE_RESIZE: "START_NODE_RESIZE",
  UPDATE_NODE_RESIZE: "UPDATE_NODE_RESIZE",
  END_NODE_RESIZE: "END_NODE_RESIZE",
  
  // Connection drag
  START_CONNECTION_DRAG: "START_CONNECTION_DRAG",
  UPDATE_CONNECTION_DRAG: "UPDATE_CONNECTION_DRAG",
  END_CONNECTION_DRAG: "END_CONNECTION_DRAG",
  
  // Connection disconnect
  START_CONNECTION_DISCONNECT: "START_CONNECTION_DISCONNECT",
  UPDATE_CONNECTION_DISCONNECT: "UPDATE_CONNECTION_DISCONNECT",
  END_CONNECTION_DISCONNECT: "END_CONNECTION_DISCONNECT",
  
  // Hover states
  SET_HOVERED_NODE: "SET_HOVERED_NODE",
  SET_HOVERED_CONNECTION: "SET_HOVERED_CONNECTION",
  SET_HOVERED_PORT: "SET_HOVERED_PORT",
  
  // Ports
  UPDATE_CONNECTED_PORTS: "UPDATE_CONNECTED_PORTS",
  
  // Context menu
  SHOW_CONTEXT_MENU: "SHOW_CONTEXT_MENU",
  HIDE_CONTEXT_MENU: "HIDE_CONTEXT_MENU",
} as const;

export type EditorActionStateActionType = typeof EDITOR_ACTION_STATE_ACTIONS[keyof typeof EDITOR_ACTION_STATE_ACTIONS];

/**
 * Action type constants for Node Canvas
 */
export const NODE_CANVAS_ACTIONS = {
  // Viewport
  SET_VIEWPORT: "SET_VIEWPORT",
  SET_OFFSET: "SET_OFFSET",
  SET_SCALE: "SET_SCALE",
  RESET_VIEWPORT: "RESET_VIEWPORT",
  
  // Canvas state
  SET_IS_PANNING: "SET_IS_PANNING",
  SET_SPACE_PRESSED: "SET_SPACE_PRESSED",
  SET_INTERACTION_MODE: "SET_INTERACTION_MODE",
} as const;

export type NodeCanvasActionType = typeof NODE_CANVAS_ACTIONS[keyof typeof NODE_CANVAS_ACTIONS];